### ISSUE TITLE
Multiple issues while trying to inject things

### ISSUE THREAD

**Issue by agzam** [zcaudate/lucidity#28]
I can't figure out how certain things work.

- injection of `vinyasa.lein` wouldn't work for me unless I add  `com.cemerick/pomegranate` as dependency, I thought `im.chit/wu.kong` supposed to make it unnecessary - apparently it didn't.

- I can't find a way to make `vinyasa.maven.pull` injection it throws following exception:

	Exception in thread "main" java.lang.ClassNotFoundException: org.apache.maven.repository.internal.MavenRepositorySystemUtils, compiling:(wu/kong/aether/session.clj:1:1)

**Comment by zcaudate** [comment]
hey agzam.

damn you're right. i haven't used vinyasa.lein myself for a while now so yeah... this is a problem.

thanks for bringing it up.

**Comment by zcaudate** [comment]
honestly, I've kinda given up on supporting vinyasa.lein there are too many versions of it going around. this might take a while. let me have a think what to do. In the meantime, don't use it and everything else will work.

**Comment by raxod502** [comment]
I would love to see this fixed as well—pulling dependencies from the REPL looks amazing 😄

My experience agrees with the OP's: I found that I can get `vinyasa.lein` injected by adding `[com.cemerick/pomegranate "0.3.1"]` as a dependency (using `[im.chit/vinyasa "0.4.7"]`). However, I can't seem to get around the `ClassNotFoundException: org.apache.maven.repository.internal.MavenRepositorySystemUtils` for `vinyasa.maven`. Also, when starting a `lein repl`, I get the following warnings: ```SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.``` Seems like these are just dependency/classpath issues, but what do I know?

**Comment by raxod502** [comment]
I also can't seem to get `vinyasa.lein` working:

```
temp.core=> (lein run)
'run' is not a task. See 'lein help'.

ExceptionInfo Suppressed exit  clojure.core/ex-info (core.clj:4617)
temp.core=> (lein help)
'help' is not a task. See 'lein help'.

ExceptionInfo Suppressed exit  clojure.core/ex-info (core.clj:4617)
``` Downgrading to `[im.chit/vinyasa "0.2.0"]` did not fix this problem, but it did get `pull` working.

**Comment by zcaudate** [comment]
`vinyasa.lein` will not work anymore. subsequently, `vinyasa.reimport` will not work either until I put in a fix.

I believe pallet/alembic supports `lein` so if you really need it, you can have add it in

what you can do is to include each library seperately as shown below I've attached my profiles.clj:

```
{:user {:plugins [[cider/cider-nrepl "0.11.0"]]
        :dependencies
        [[org.clojure/tools.nrepl "0.2.12"]
         [org.clojure/tools.namespace "0.2.11"]
         [spyscope "0.1.5"]
         [im.chit/vinyasa.inject     "0.4.7"]
         [im.chit/vinyasa.reflection "0.4.7"]
         [im.chit/vinyasa.debug      "0.4.7"]
         [im.chit/vinyasa.maven      "0.4.7"]]
        :injections
        [(require 'spyscope.core)
         (require '[vinyasa.inject :as inject])
         (inject/in [vinyasa.inject :refer [inject [in inject-in]]]
                    [clojure.pprint pprint]
                    [clojure.java.shell sh]
                    [vinyasa.maven pull]
                    [clojure.tools.namespace.repl refresh]
                    [clojure.repl doc source]

                    clojure.core
                    [vinyasa.reflection .& .> .? .* .% .%>]

                    clojure.core
                    [vinyasa.debug :refer [[dbg-> *->] [dbg->> *->>]]])]

         :deploy-repositories {"clojars"  {:signing {:gpg-key "27C3C4C6"}
                                           :creds :gpg}}}}
```

**Comment by raxod502** [comment]
Thanks so much for this! Works like a charm. After a few hours I eventually hammered out this [profiles.clj](https://github.com/raxod502/dotfiles/blob/master/.lein/profiles.clj), which covers all of my needs.

**Comment by zcaudate** [comment]
wow.

that’s super nice! what are you using for taking care of the modularity?

**Comment by raxod502** [comment]
Nothing special -- out of the box, Leiningen lets you define a profile as a vector of keywords representing other profiles, so I can build the `:awesome` profile out of a bunch of smaller profiles. It's discussed [here](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#composite-profiles) in the Leiningen documentation.

I really like this approach because it makes `lein repl` really fast, whereas if I just want to connect to an editor without too much extra startup time I can `lein with-profile +cider repl`, or maybe when I'm investigating a new library but not really debugging I could `lein with-profile +cider,+inject repl`, or... the possibilities are endless. And then of course you can make as many composite profiles like `:awesome` as you want, for quick use.

I added [this code](https://github.com/raxod502/dotfiles/commit/edd3a9274b36021cad2bb3047bc1bff2f16c1f19#diff-b664d6253925d6ccf46c39a4b1a2c854) to my [`init.el`](https://github.com/raxod502/dotfiles/blob/master/.emacs.d/init.el) to support the setup.

**Comment by zcaudate** [comment]
yeah… that’s super cool

I would love if you can send a PR documenting how you have set up your
workflow.


On 2 Aug 2016, at 7:30 AM, Radon Rosborough <notifications@github.com>
wrote:

Nothing special -- out of the box, Leiningen lets you define a profile as a
vector of keywords representing other profiles, so I can build the :awesome
profile out of a bunch of smaller profiles. It's discussed here
<http://t.signauxdeux.com/e1t/c/5/f18dQhb0SmZ58dDMPbW2n0x6l2B9nMJW7sM9dn7dK_MMdBzM2-04?t=https%3A%2F%2Fgithub.com%2Ftechnomancy%2Fleiningen%2Fblob%2Fmaster%2Fdoc%2FPROFILES.md%23composite-profiles&si=5764797642309632&pi=27c5a260-17b0-4744-f356-23a40d116560>
in the Leiningen documentation.

I really like this approach because it makes lein repl really fast, whereas
if I just want to connect to an editor without too much extra startup time
I can lein with-profile +cider repl, or maybe when I'm investigating a new
library but not really debugging I could lein with-profile +cider,+inject
repl, or... the possibilities are endless. And then of course you can make
as many composite profiles like :awesome as you want, for quick use.

I added this code
<http://t.signauxdeux.com/e1t/c/5/f18dQhb0SmZ58dDMPbW2n0x6l2B9nMJW7sM9dn7dK_MMdBzM2-04?t=https%3A%2F%2Fgithub.com%2Fraxod502%2Fdotfiles%2Fcommit%2Fedd3a9274b36021cad2bb3047bc1bff2f16c1f19%23diff-b664d6253925d6ccf46c39a4b1a2c854&si=5764797642309632&pi=27c5a260-17b0-4744-f356-23a40d116560>
to my init.el
<https://github.com/raxod502/dotfiles/blob/master/.emacs.d/init.el> to
support the setup.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<http://t.signauxdeux.com/e1t/c/5/f18dQhb0SmZ58dDMPbW2n0x6l2B9nMJW7sM9dn7dK_MMdBzM2-04?t=https%3A%2F%2Fgithub.com%2Fzcaudate%2Fvinyasa%2Fissues%2F28%23issuecomment-236740557&si=5764797642309632&pi=27c5a260-17b0-4744-f356-23a40d116560>,
or mute the thread
<http://t.signauxdeux.com/e1t/c/5/f18dQhb0SmZ58dDMPbW2n0x6l2B9nMJW7sM9dn7dK_MMdBzM2-04?t=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABY11Jjqy4ctI01N6y6EEK25Qj_G64e_ks5qboGOgaJpZM4JNu0u&si=5764797642309632&pi=27c5a260-17b0-4744-f356-23a40d116560>
.

**Comment by raxod502** [comment]
It's funny you should ask that, since before a couple of hours ago I didn't **have** a workflow for Leiningen—[this](https://github.com/raxod502/dotfiles/blob/cae879389fc148959350c187a65bb62d40e2557d/.lein/profiles.clj) was my `profiles.clj` before that last commit 😄.

When you say a pull request, do you mean to this repository? What would that entail?

As you can see [here](https://github.com/raxod502/dotfiles/pulse), my newly created [dotfiles](https://github.com/raxod502/dotfiles) repository is undergoing fairly rapid development at the moment. After it starts to stabilize, I'm planning on adding a proper `README.md` explaining what all the different parts are and how to use them. That may be more appropriate for workflow documentation.

**Comment by zcaudate** [comment]
cool. feel free to add the link to the vinyasa readme once you have figured out the best solution
