### ISSUE TITLE
Can't reload java source files

### ISSUE THREAD

**Issue by Hardikus** [zcaudate/lucidity#29]
Hello,

I'm trying to follow tutorial[1] to reload java source files in my Cursive REPL. I've installed lib. and added :java-source-paths in project.clj. But when i start REPL and try to use (vinyasa.reimport/reimport), it throws below error: 

CompilerException java.lang.ClassNotFoundException: org.apache.maven.repository.internal.DefaultServiceLocator, compiling:(cemerick/pomegranate/aether.clj:1:1)

I think it's something to do with leiningen as dependency, but not able to solve.

If you've any idea about why is this happening, please help. 

Thanks,
Hardik

[1] http://z.caudate.me/dynamic-reloading-of-java-code-in-emacsnrepl/

**Comment by zcaudate** [comment]
this needs fixing... sorry this facet has been neglected for a while.

it's referenced here, along with a couple of other issues.

https://github.com/zcaudate/vinyasa/issues/28

this can be fixed by copying part of https://github.com/technomancy/leiningen/blob/master/src/leiningen/compile.clj over. I'll take a look at it when I get the time but please feel free to have a go if you are inclined to fix it =P

**Comment by Hardikus** [comment]
adding `com.cemerick/pomegranate` dependency works for now. 

I can spend time to fix this, however i don't see how (this area is still new to me). from what you say, i feel that we need to remove `leiningen.javac` dependency from `reimport` namespace, by coping parts from `leiningen.compile`, i don't know how or if i'm thinking correct.

If you provide more information about what you see as solution, i can work on it. 

Thanks, Reloading java files in REPL is really helpful.

**Comment by zcaudate** [comment]
i'm closing this for now
